"""added sprite_path field to Pokemon table

Revision ID: 0b1870e2b064
Revises: aa79ccb2150d
Create Date: 2024-05-12 09:31:16.207039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1870e2b064'
down_revision = 'aa79ccb2150d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sprite_path', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_pokemon_sprite_path'), ['sprite_path'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pokemon_sprite_path'))
        batch_op.drop_column('sprite_path')

    # ### end Alembic commands ###
