"""Added tokens field to User table

Revision ID: 285668093583
Revises: 0b1870e2b064
Create Date: 2024-05-12 09:35:16.207039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285668093583'
down_revision = '0b1870e2b064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tokens', sa.Integer(), nullable=False, server_default="10"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('tokens')

    # ### end Alembic commands ###
