"""empty message

Revision ID: 508d11b12645
Revises: 285668093583
Create Date: 2024-05-18 12:25:30.040922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508d11b12645'
down_revision = '285668093583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coins', sa.Integer(), nullable=False, server_default="10"))
        batch_op.drop_column('tokens')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tokens', sa.INTEGER(), server_default=sa.text("'10'"), nullable=False))
        batch_op.drop_column('coins')

    op.create_table('_alembic_tmp_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('coins', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), nullable=True),
    sa.Column('about_me', sa.VARCHAR(length=140), nullable=True),
    sa.Column('last_seen', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
