"""pokemon_id are referenced rather than name in trade table

Revision ID: 63e731294e79
Revises: 78f5d1d9ff82
Create Date: 2024-05-02 11:35:46.498770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63e731294e79'
down_revision = '78f5d1d9ff82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pokemon_id1', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('pokemon_id2', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_trade_pokemon_id1'), ['pokemon_id1'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_pokemon_id2'), ['pokemon_id2'], unique=False)
        batch_op.create_foreign_key('fk_trade_pokemon_id1', 'pokemon', ['pokemon_id1'], ['id'])
        batch_op.create_foreign_key('fk_trade_pokemon_id2', 'pokemon', ['pokemon_id2'], ['id'])
        batch_op.drop_column('pokemon2')
        batch_op.drop_column('pokemon1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pokemon1', sa.VARCHAR(length=32), nullable=False))
        batch_op.add_column(sa.Column('pokemon2', sa.VARCHAR(length=32), nullable=False))
        batch_op.drop_constraint('fk_trade_pokemon_id2', type_='foreignkey')
        batch_op.drop_constraint('fk_trade_pokemon_id1', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_trade_pokemon_id2'))
        batch_op.drop_index(batch_op.f('ix_trade_pokemon_id1'))
        batch_op.drop_column('pokemon_id2')
        batch_op.drop_column('pokemon_id1')

    # ### end Alembic commands ###
