"""made user_id2 in Trade table optional

Revision ID: aa79ccb2150d
Revises: c15a01c3a36c
Create Date: 2024-05-04 18:13:55.666432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa79ccb2150d'
down_revision = 'c15a01c3a36c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.alter_column('user_id2',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.alter_column('user_id2',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
