"""pokemon table and edited trade table

Revision ID: f5fd9ef1d3a1
Revises: b82fb53467ab
Create Date: 2024-04-30 13:13:40.951061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5fd9ef1d3a1'
down_revision = 'b82fb53467ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pokedex_num', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('shiny', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pokemon_name'), ['name'], unique=True)

    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pokemon1', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('pokemon2', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('user_id1', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id2', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_trade_user_id')
        batch_op.create_index(batch_op.f('ix_trade_user_id1'), ['user_id1'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_user_id2'), ['user_id2'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id1'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id2'], ['id'])
        batch_op.drop_column('received')
        batch_op.drop_column('user_id')
        batch_op.drop_column('gave')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gave', sa.VARCHAR(length=140), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('received', sa.VARCHAR(length=140), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_trade_user_id2'))
        batch_op.drop_index(batch_op.f('ix_trade_user_id1'))
        batch_op.create_index('ix_trade_user_id', ['user_id'], unique=False)
        batch_op.drop_column('user_id2')
        batch_op.drop_column('user_id1')
        batch_op.drop_column('pokemon2')
        batch_op.drop_column('pokemon1')

    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pokemon_name'))

    op.drop_table('pokemon')
    # ### end Alembic commands ###
